# Generated by Django 3.2.7 on 2022-07-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=300, null=True)),
                ('song_lyrics', models.CharField(max_length=300, null=True)),
                ('song_artist', models.CharField(max_length=300, null=True)),
                ('time_stamp', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
